import Layout from '@/components/Layout'
import Head from 'next/head'
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMeButton from '@/components/HireMeButton';
import TransitionEffect from '@/components/TransitionEffect';

export default function Home() {
  return (
    <>
      <Head>
        <title>Charlie&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TransitionEffect />

      <main className='flex items-center text-dark min-h-screen dark:text-light'>
        <Layout className='pt-0 md:p-16 sm:pt-8'>
          <div className='flex w-full lg:flex-col'>
            {/* Left Side: Title & Description */}
            <div className='w-1/2 flex flex-col justify-center lg:w-full lg:mb-8 ml-12 sm:ml-0'>
              <AnimatedText
                text="On a Mission to Build and Improve Web3"
                className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'
              />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                As a technical content writer specializing in web3, I aim to bridge
                the gap between complex technology and a wider audience. With a strong
                foundation in Solidity, Foundry, and JavaScript, I leverage my development
                experience to create informative and engaging content. Explore my latest
                articles and research, where I delve into the intricacies of web3 and its
                potential to shape the future.
              </p>
              <div className='flex items-center mt-2'>
                <Link
                  href="https://docs.google.com/document/d/1e0JpO-gUkPv4W76YErJFTBYMzhAsi82eWUyDpgsgItg/edit?usp=sharing"
                  target={'_blank'}
                  className='flex items-center bg-dark text-light p-2.5 px-6
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
                  border-2 border-solid border-transparent hover:border-dark
                  dark:text-dark dark:bg-light hover:dark:bg-dark 
                  hover:dark:text-light hover:dark:border-blue mr-4 md:p-2 md:px-4 md:text-base'
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:charliej.dev@outlook.com"
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'
                >
                  Contact
                </Link>
              </div>
            </div>
            {/* Right Side: Cards */}
            <div className='w-1/2 flex flex-col items-center justify-center gap-6 lg:w-full '>
              <div className='bg-light dark:bg-dark border border-dark dark:border-light rounded-lg shadow-md p-6 w-90 flex flex-col items-center
                hover:scale-105 hover:shadow-xl hover:border-blue hover:dark:border-blue hover:border-2 hover:dark:border-2 transition-transform duration-300'>
                <h3 className='text-3xl font-bold mb-2'>Technical Writing</h3>
                <p className='text-sm mb-4 text-center'>Read my latest articles and research on topics of web3, DeFi, and blockchain development.</p>
                <Link
                  href="/writing"
                  className='text-blue-600 dark:text-blue-400 underline font-medium'
                >
                  View Writing
                </Link>
              </div>
              <div className='bg-light dark:bg-dark border border-dark dark:border-light rounded-lg shadow-md p-6 w-90 flex flex-col items-center
                hover:scale-105 hover:shadow-xl hover:border-blue hover:dark:border-blue hover:border-2 hover:dark:border-2 transition-transform duration-300'>
                <h3 className='text-3xl font-bold mb-2'>Dev Projects</h3>
                <p className='text-sm mb-4 text-center'>Explore my portfolio of web3 development projects written and open-source contributions.</p>
                <Link
                  href="/projects"
                  className='text-blue-600 dark:text-blue-400 underline font-medium'
                >
                  View Projects
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMeButton />
      </main>
    </>
  )
}
